### ISSUE TITLE
[BUG] Fix back button url after changing route params

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1451]
**Describe the bug**
When changing route params and going to a child route, the back URL will go to the wrong route param.

**To Reproduce**

1. Go to a page with a route param
2. Change route param
2. Navigate to nested route
3. Click back url
4. See you end up on page from step 1

**Kirby version**
- 1.4.32

**Expected behavior**
Should go back to latest route param

**Screenshots**

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**
We need the:
`{ provide: RouteReuseStrategy, useClass: IonicRouteStrategy }`

Which is the default in all the Ionic starter apps to ensure route param changes are updating the page stack.

## Tasks:
- [ ] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by alxzak** [comment]
Consider if #1135 - hidebackbutton should disable bezel-swipe should be fixed together with this.

**Comment by RasmusKjeldgaard** [comment]
Can no longer seem to reproduce, please open a new issue if problem persists.
